### ISSUE TITLE
Feature request: show url's and exp_id

### ISSUE THREAD

**Issue by MKaptein** [Nth-iteration-labs/streamingbandit-ui#1]
This is just a feature request since it was not easily seen in the current screenshot that I have:

It would be great if a) the exp_id is clearly visible in the from end, and b) properly formatted example of the getaction and setreward queries can easily be obtained for each experiment.

**Comment by robinvanemden** [comment]
The features were already implemented at the time, yet the screenshot appears to have been cropped, rendering these fields invisible.
