### ISSUE TITLE
Show example output in front-end?

### ISSUE THREAD

**Issue by MKaptein** [Nth-iteration-labs/streamingbandit-ui#14]
Hi,

When people fill out the "get context" and get action fields, as well as the "default reward" it is not immediately clear what is expected. E.g., do we expect 
```
self.context["bla"] = 10
```
or do we expect
```
{"bla":"10"}
```
(or something else). Maybe we can make this visually clear in some way?

**Comment by robinvanemden** [comment]
I added inline field formatting info to the "default reward" field. Concerning the other calls: I am not sure this should be addressed in the frontend? If other users will be like me, they'll first take a look at the defaults to see how they define these fields. And then refer to the documentation if that would not suffice?

**Comment by MKaptein** [comment]
Yes, I guess a good default and good docs jointly suffice!

Maurits
