### ISSUE TITLE
Login should show address of the remote back-end

### ISSUE THREAD

**Issue by MKaptein** [Nth-iteration-labs/streamingbandit-ui#5]
It is currently upon login unclear "where" you are logging in; this makes it difficult to know which server you are addressing when logging in.

**Comment by g0ulash** [comment]
Maybe also an option to configure the address in the login screen?

**Comment by robinvanemden** [comment]
You can now set the server address in the login screen, and the URL of the server is shown on the welcome screen.

PS: setting the server address currently makes use of browsers' localStorage. So though the value is stored and saved and across browser sessions, on cleaning the cache the client falls back to a default of http://localhost:8080.
