### ISSUE TITLE
Informative error message when loggin in with wrong uname and pass

### ISSUE THREAD

**Issue by MKaptein** [Nth-iteration-labs/streamingbandit-ui#6]
(Perhaps also back-end?)

In any case, we now have no real feedback when logging in; would be nice to at least show whether (e.g.,) the username and pass were not ok.

**Comment by g0ulash** [comment]
The back-end will raise the following error (so it's already settled there):
```
raise ExceptionHandler(reason="Wrong username or password!", status_code=401)
```
