### ISSUE TITLE
Clicking on "Experiments" in empty installation gives "internal server error"

### ISSUE THREAD

**Issue by MKaptein** [Nth-iteration-labs/streamingbandit-ui#8]
When logging in to a fresh new back-end instance clicking on "experiments" give a "internal server error": basically this call:
```
http://localhost:8080/exp?_end=10&_order=DESC&_sort=id&_start=0
```
apparently fails. Perhaps its back-end?

**Comment by robinvanemden** [comment]
Can you paste the relevant server's stack trace? Either from the StreamingBandit server log, or from the browser's developers log? If I empty "my" server's experiments list, it seems fine:
![image](https://user-images.githubusercontent.com/95014/30868818-f51539b4-a2df-11e7-90db-fa19e876f2ec.png)

**Comment by MKaptein** [comment]
But, I must be doing more wrong…

See this image; the defaults list is empty, but the server does actually serve the JSON object containing the defaults…

**Comment by MKaptein** [comment]
Hey, here is a picture…

http://localhost:8080/exp?_end=10&_order=DESC&_sort=id&_start=0 <http://localhost:8080/exp?_end=10&_order=DESC&_sort=id&_start=0>

seems to give an internal server error

**Comment by robinvanemden** [comment]
The pictures somehow seem to have gotten lost in translation :)
This nevertheless sounds suspiciously like yet another CORS related problem.
If so, we might do something along these lines in the "set_default_headers" function in basehandler.py:

```
        if not origin: 
            origin = "http://request.has.no.origin.com" 
        self.set_header("Access-Control-Allow-Origin", origin)
```

But the StreamingBandit server log entry for this call would help pinpoint the issue. Or enable the "Web Developer" tools, and take a look at the response body the server sends at the time of this error - it should contain a JSON trace log. When all goes well, it looks like this:

![image](https://user-images.githubusercontent.com/95014/30870832-3a12e7fa-a2e5-11e7-9fbb-e054bdddd154.png)

**Comment by robinvanemden** [comment]
This has been fixed server side, see: https://github.com/Nth-iteration-labs/streamingbandit/issues/55#issuecomment-332787174
